### ISSUE TITLE
Frontend To-Do от 18 мая

### ISSUE THREAD

**Issue by DaryaFilimonova7** [DaryaFilimonova7/HSE_Project_Website#1]
- [x] Страница каталога активных заявок (active-projects.html + projects.css)
- [x] Страница каталога архивных заявок (archived-projects.html + projects.css)
- [x] Страница проекта, пример (project_example.html + project-page.css)
- [x] Страница личного кабинета (profile)
- [x] Страница создания аккаунта (create-account)
- [x] Страница заполнения заявки на проект (application)

- [x] Окно авторизации

у трех последних одноименные CSS-файлы, которые уже к ним подключены
JS-файлы можно добавить при необходимости
index.html готов, изменения в styles.css требуют согласования 😎
